"use client";

import { useEffect, useState } from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Underline from "@tiptap/extension-underline";
import TextAlign from "@tiptap/extension-text-align";
import { TextStyle } from "@tiptap/extension-text-style";
import FontFamily from "@tiptap/extension-font-family";
import Color from "@tiptap/extension-color";
import Highlight from "@tiptap/extension-highlight";
import ChatPanel from "@/components/chatpanel/page";

export default function LegalEditorPage() {
  const [mounted, setMounted] = useState(false);
  const [aiSuggestion, setAiSuggestion] = useState<string | null>(null);
  const [title, setTitle] = useState("Legal Document");
  const [isSaved, setIsSaved] = useState(true);

  useEffect(() => {
    setMounted(true);
  }, []);

  const editor = useEditor({
    immediatelyRender: false,
    editable: mounted,
    extensions: [
      StarterKit.configure({
        paragraph: {
          HTMLAttributes: {
            class: "paragraph",
          },
        },
        heading: {
          HTMLAttributes: {
            class: "heading",
          },
        },
        bulletList: {
          HTMLAttributes: {
            class: "bullet-list",
          },
        },
        orderedList: {
          HTMLAttributes: {
            class: "ordered-list",
          },
        },
      }),
      Underline.configure({
        HTMLAttributes: {
          class: "underline",
        },
      }),
      TextStyle,
      FontFamily,
      Color,
      Highlight.configure({
        multicolor: true,
        HTMLAttributes: {
          class: "highlight",
        },
      }),
      TextAlign.configure({
        types: ["heading", "paragraph"],
      }),
    ],
    content: `
      <h2>LEGAL DOCUMENT DRAFT</h2>
      <p>This draft was generated by the system. You may edit it or ask the AI to refine it.</p>
      <p>Start typing to edit this document...</p>
    `,
    onUpdate: () => setIsSaved(false),
  });

  if (!mounted || !editor) return null;

  const handleSave = () => {
    setIsSaved(true);
    // TODO: Add actual save functionality
  };

  const handleExport = () => {
    // TODO: Add export functionality
    console.log("Exporting document:", title);
  };

  return (
    <div className="h-screen flex flex-col bg-white">
      {/* HEADER */}
      <header className="flex items-center justify-between px-8 py-5 border-b border-gray-300 bg-white shadow-sm">
        <div className="flex-1">
          <input
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="text-2xl font-bold outline-none bg-transparent text-black placeholder-gray-400 w-full"
            placeholder="Document Title"
          />
          <p className="text-xs text-gray-600 mt-1">Last edited moments ago</p>
        </div>

        <div className="flex items-center gap-4 ml-8">
          <span className={`text-sm font-semibold flex items-center gap-2 ${isSaved ? "text-gray-700" : "text-gray-500"}`}>
            {isSaved ? (
              <>
                <span className="w-2 h-2 rounded-full bg-black"></span>
                All changes saved
              </>
            ) : (
              <>
                <span className="w-2 h-2 rounded-full bg-gray-400 animate-pulse"></span>
                Unsaved changes
              </>
            )}
          </span>
          <button
            onClick={handleSave}
            className="px-4 py-2 bg-black hover:bg-gray-900 text-white rounded border border-black font-medium text-sm transition"
          >
            Save
          </button>
          <button
            onClick={handleExport}
            className="px-4 py-2 bg-white border border-black text-black hover:bg-gray-100 rounded font-medium text-sm transition"
          >
            Export
          </button>
        </div>
      </header>

      <div className="flex flex-1 overflow-hidden">
        {/* EDITOR COLUMN */}
        <div className="flex-1 flex flex-col overflow-hidden bg-gray-50">
          {/* TOOLBAR */}
          <div className="border-b border-gray-300 bg-white px-6 py-3 shadow-sm">
            <div className="flex flex-wrap items-center gap-1">
              {/* Formatting Group */}
              <div className="flex items-center gap-1 pr-3 border-r border-gray-300">
                <ToolbarButton
                  title="Bold (Ctrl+B)"
                  icon="B"
                  isActive={editor.isActive("bold")}
                  onClick={() => editor.chain().focus().toggleBold().run()}
                />
                <ToolbarButton
                  title="Italic (Ctrl+I)"
                  icon="I"
                  isActive={editor.isActive("italic")}
                  onClick={() => editor.chain().focus().toggleItalic().run()}
                />
                <ToolbarButton
                  title="Underline (Ctrl+U)"
                  icon="U"
                  isActive={editor.isActive("underline")}
                  onClick={() => editor.chain().focus().toggleUnderline().run()}
                />
                <ToolbarButton
                  title="Strikethrough"
                  icon="S"
                  isActive={editor.isActive("strike")}
                  onClick={() => editor.chain().focus().toggleStrike().run()}
                />
              </div>

              {/* Alignment Group */}
              <div className="flex items-center gap-1 px-3 border-r border-gray-300">
                <ToolbarButton
                  title="Align Left"
                  icon="◀"
                  isActive={editor.isActive({ textAlign: "left" })}
                  onClick={() => editor.chain().focus().setTextAlign("left").run()}
                />
                <ToolbarButton
                  title="Align Center"
                  icon="◆"
                  isActive={editor.isActive({ textAlign: "center" })}
                  onClick={() => editor.chain().focus().setTextAlign("center").run()}
                />
                <ToolbarButton
                  title="Align Right"
                  icon="▶"
                  isActive={editor.isActive({ textAlign: "right" })}
                  onClick={() => editor.chain().focus().setTextAlign("right").run()}
                />
                <ToolbarButton
                  title="Justify"
                  icon="≡"
                  isActive={editor.isActive({ textAlign: "justify" })}
                  onClick={() => editor.chain().focus().setTextAlign("justify").run()}
                />
              </div>

              {/* Lists Group */}
              <div className="flex items-center gap-1 px-3 border-r border-gray-300">
                <ToolbarButton
                  title="Bullet List"
                  icon="•"
                  isActive={editor.isActive("bulletList")}
                  onClick={() => editor.chain().focus().toggleBulletList().run()}
                />
                <ToolbarButton
                  title="Ordered List"
                  icon="1"
                  isActive={editor.isActive("orderedList")}
                  onClick={() => editor.chain().focus().toggleOrderedList().run()}
                />
              </div>

              {/* Headings Group */}
              <div className="flex items-center gap-1 px-3 border-r border-gray-300">
                <ToolbarButton
                  title="Heading 1"
                  icon="H1"
                  isActive={editor.isActive("heading", { level: 1 })}
                  onClick={() => editor.chain().focus().setHeading({ level: 1 }).run()}
                />
                <ToolbarButton
                  title="Heading 2"
                  icon="H2"
                  isActive={editor.isActive("heading", { level: 2 })}
                  onClick={() => editor.chain().focus().setHeading({ level: 2 }).run()}
                />
              </div>

              {/* Clear Format */}
              <div className="flex items-center gap-1 px-3">
                <ToolbarButton
                  title="Clear Formatting"
                  icon="✕"
                  onClick={() => editor.chain().focus().unsetAllMarks().clearNodes().run()}
                />
              </div>
            </div>
          </div>

          {/* EDITOR AREA */}
          <div className="flex-1 overflow-auto p-12 bg-gray-50">
            <div
              className="mx-auto bg-white border border-gray-400 shadow-lg"
              style={{
                width: "210mm",
                minHeight: "297mm",
                padding: "48px",
              }}
            >
              <EditorContent
                editor={editor}
                className="editor-content text-black text-base leading-relaxed"
              />
            </div>
          </div>

          {/* AI SUGGESTION PANEL */}
          {aiSuggestion && (
            <div className="border-t border-gray-300 bg-white p-6 shadow-inner">
              <div className="flex items-start justify-between mb-4">
                <p className="text-sm font-bold text-black flex items-center gap-2">
                  <span className="inline-block w-2 h-2 rounded-full bg-black"></span>
                  AI Suggestion
                </p>
              </div>
              <p className="text-sm text-gray-800 mb-4 leading-relaxed whitespace-pre-wrap">{aiSuggestion}</p>
              <div className="flex gap-3">
                <button
                  onClick={() => {
                    editor.chain().focus().insertContent(aiSuggestion).run();
                    setAiSuggestion(null);
                  }}
                  className="px-4 py-2 bg-black text-white rounded border border-black hover:bg-gray-900 font-medium text-sm transition"
                >
                  ✓ Accept
                </button>
                <button
                  onClick={() => setAiSuggestion(null)}
                  className="px-4 py-2 bg-white border border-gray-400 text-black rounded hover:bg-gray-100 font-medium text-sm transition"
                >
                  ✕ Reject
                </button>
              </div>
            </div>
          )}
        </div>

        {/* AI CHAT PANEL */}
        <ChatPanel editor={editor} setAiSuggestion={setAiSuggestion} />
      </div>
    </div>
  );
}

/* TOOLBAR BUTTON */
function ToolbarButton({
  title,
  icon,
  onClick,
  isActive = false,
}: {
  title: string;
  icon: string;
  onClick: () => void;
  isActive?: boolean;
}) {
  return (
    <button
      onClick={onClick}
      title={title}
      className={`px-3 py-2 rounded text-sm font-medium border transition ${
        isActive
          ? "bg-black text-white border-black"
          : "bg-white text-black border-gray-300 hover:border-black hover:bg-gray-100"
      }`}
    >
      {icon}
    </button>
  );
}
